[package]
name = "cogito"
version = "0.1.0"
edition = "2021"


[profile.release]
debug = 2

[dependencies]
macroquad = "0.3.23"
hecs = { path = "../hecs" }

rapier2d = { version = "0.14", features = [ "simd-stable" ] }